name: nexo-base pytorch-cpu

on:
  push:
    branches: 
      - pytorch-cpu

jobs:
  build:
    name: Build on Ubuntu
    runs-on: ubuntu-18.04
    steps:
      - name: Docker login
        run: echo '${{ secrets.DOCKERHUB_ACCESSTOK }}' | docker login --username heather999 --password-stdin
      - name: checkout nexo-base
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: do docker build
        run: docker build --build-arg GH_USER=heather999 --build-arg GH_TOKEN=${{ secrets.GH_TOKEN }} --no-cache -t heather999/nexo-base:pytorch-cpuonly -f $GITHUB_WORKSPACE/Dockerfile . 
      - name: Docker push
        run: docker push heather999/nexo-base:pytorch-cpuonly
       
